### ISSUE TITLE
Question about part of the code

### ISSUE THREAD

**Issue by lldelisle** [deeptools/HiCMatrix#28]
Hi,
Could you tell me what this is suppose to do? (This is in the save method).

https://github.com/deeptools/HiCMatrix/blob/811a9a8dbbdd4f13c548d886795d019060b9a922/hicmatrix/lib/cool.py#L309-L317

**Comment by joachimwolff** [comment]
This was part of something to have a feature to scale the values to whatever value range the user wants to during the computation but in the end the data should be stored in a way it was originally.  However, I removed it now, because in the load I realized I only use it for a workaround of a bug I recently discovered and it is better to have that one fixed.

**Comment by lldelisle** [comment]
But there is still a rescaling which happens sometimes:
https://github.com/deeptools/HiCMatrix/blob/811a9a8dbbdd4f13c548d886795d019060b9a922/hicmatrix/lib/cool.py#L199-L216
I think sometimes you want to original range not the rescaled, I wanted to make a PR to save some values which will allow to go back to original values but I wanted to be sure this did not exist already.

**Comment by joachimwolff** [comment]
So this is removed in the current bug fix branch, not in master or dev so far. However, at the end of the day I should have a new release.
